<?php

declare(strict_types=1);

namespace Plugins\Pageflow\Tests;

use Plugins\Ground\Ground\PluginGroundTestCase;
use Plugins\Pageflow\Provider;

/**
 * Ground tests for the pageflow plugin.
 *
 * Generated by `make:ground-test` from module.json. Each test names
 * something the manifest declares; fill in the bodies.
 */
final class PageflowGroundTest extends PluginGroundTestCase
{
    protected function plugin(): string
    {
        return Provider::class;
    }

    /**
     * Providers for: vite.manifest, i18n.translation
     *
     * Every required domain must be registered or the boot fails — that is
     * the kernel enforcing the dependency, not the harness being strict.
     */
    protected function dependencies(): array
    {
        return [
            \Plugins\ViteManifest\Provider::class,
            \Plugins\I18n\Provider::class,
        ];
    }

    public function testItBoots(): void
    {
        $this->assertNotSame('', $this->ground()->manifest()->solves());
    }

    public function testGETPageflowCsrf(): void
    {
        $this->assertRouteExists('GET', '/pageflow/csrf');

        $response = $this->ground()->get('/pageflow/csrf');

        $this->assertOk($response);
        // The endpoint's whole job: hand the client a token it can put in a
        // header. A 200 with no token would still pass assertOk().
        self::assertNotSame('', (string) $response->at('token'));
    }

    public function testGETPageflowStream(): void
    {
        $this->assertRouteExists('GET', '/pageflow/stream');

        // $response = $this->ground()->get('/pageflow/stream');
        // $this->assertOk($response);
    }

    public function testItResolvesPageflowResponder(): void
    {
        // Resolving in the plugin's own scope — the only scope that
        // may reach its bindInternal() dependencies.
        $this->assertInstanceOf(
            \Plugins\Pageflow\Http\PageflowResponder::class,
            $this->ground()->service(\Plugins\Pageflow\Http\PageflowResponder::class),
        );
    }

    public function testItResolvesPageflowChannel(): void
    {
        // Resolving in the plugin's own scope — the only scope that
        // may reach its bindInternal() dependencies.
        $this->assertInstanceOf(
            \Plugins\Pageflow\Http\PageflowChannel::class,
            $this->ground()->service(\Plugins\Pageflow\Http\PageflowChannel::class),
        );
    }
}
